import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import axios from 'axios'
import {useState, useEffect, useRef} from 'react'

const Home: NextPage = () => {
  const [npcs, setNPCS] = useState(null)

  useEffect(() => {
    axios.get("http://localhost:8080/npcs").then((res) => {
      setNPCS(res.data)
    })
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={`block rounded-xl flex flex-col mx-16 bg-green-600`}>
          <div className={`block rounded-xl m-4 w-80 h-8 p-2 bg-green-100 ${styles.outputLog}`}>
            {npcs[0].name}
          </div>
          <input className="block rounded-xl m-4 mt-0 w-80 h-8 p-2 bg-white border border-border transparent focus:outline-none" placeholder="..." />
          <button className="block rounded-xl m-4 mt-0 w-80 p-2 bg-green-300 hover:bg-green-400 text-center font-extrabold"> submit </button>
        </div>
      </main>
    </div>
  )
}

export default Home
